openapi: "3.0.3"
info:
  title: C-2-2[B] API
  version: "0.0.1"
servers:
  - url: https://api.server.test/v1
paths:
#  /login:
#    $ref: "./paths/login.yaml"
  /{targetDataModel}:
    $ref: "./paths/targetDataModel.yaml"
components:
  schemas:
    authentication.Information:
      $ref: "./components/schemas/authentication/information.yaml#/information"
    authentication.Token:
      $ref: "./components/schemas/authentication/token.yaml#/token"
    dataModel.spots:
      $ref: "./components/schemas/dataModel/spots.yaml#/spots"
    dataModel.maps:
      $ref: "./components/schemas/dataModel/maps.yaml#/maps"
    dataModel.hdmaps:
      $ref: "./components/schemas/dataModel/hdmaps.yaml#/hdmaps"
    dataModel.traffics:
      $ref: "./components/schemas/dataModel/traffics.yaml#/traffics"
    dataModel.trafficcontrols:
      $ref: "./components/schemas/dataModel/trafficcontrols.yaml#/trafficcontrols"
    dataModel.pointclouds:
      $ref: "./components/schemas/dataModel/pointclouds.yaml#/pointclouds"
    dataModel.weatherrisks:
      $ref: "./components/schemas/dataModel/weatherrisks.yaml#/weatherrisks"
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: apiKey
      in: header
    Authorization:
      type: http
      scheme: bearer
      description: アクセストークン発行APIで発行したアクセストークン
