openapi: "3.0.3"
info:
  title: C-2-2[B] API
  version: "0.0.1"
servers:
  - url: https://api.server.test/v1
paths:
  /{targetDataModel}:
    $ref: "./paths/targetDataModel.yaml"
  /map/{dataType}/{z}/{x}/{y}.pbf:
    $ref: "./paths/map.yaml"
  /pointcloud:
    $ref: "./paths/PointCloud.yaml"
  /login:
    $ref: "./paths/login.yaml"
  # /hdlanecenter:
  #   $ref: "./paths/HDLaneCenter.yaml"
  # /facade:
  #   $ref: "./paths/facade.yaml"
components:
  schemas:
    authentication.Information:
      $ref: "./components/schemas/authentication/information.yaml#/information"
    authentication.Token:
      $ref: "./components/schemas/authentication/token.yaml#/token"
    dataModel.bbox:
      $ref: "./components/schemas/dataModel/bbox.yaml#/bbox"
    dataModel.voxel:
      $ref: "./components/schemas/dataModel/voxel.yaml#/voxel"
    dataModel.mesh:
      $ref: "./components/schemas/dataModel/mesh.yaml#/mesh"
    dataModel.city:
      $ref: "./components/schemas/dataModel/city.yaml#/city"
    dataModel.roadlink:
      $ref: "./components/schemas/dataModel/roadlink.yaml#/roadlink"
    dataModel.reg:
      $ref: "./components/schemas/dataModel/reg.yaml#/reg"
    dataModel.facade:
      $ref: "./components/schemas/dataModel/facade.yaml#/facade"
    dataModel.hdlanecenter:
      $ref: "./components/schemas/dataModel/hdlanecenter.yaml#/hdlanecenter"
    dataModel.hdlaneline:
      $ref: "./components/schemas/dataModel/HDLaneLine.yaml#/hdlaneline"
    dataModel.weatherrisks:
      $ref: "./components/schemas/dataModel/weatherrisks.yaml#/weatherrisks"
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: apiKey
      in: header
    Authorization:
      type: http
      scheme: bearer
      description: アクセストークン発行APIで発行したアクセストークン
